import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { aiEngine } from "@/lib/ai";

export async function GET() {
  try {
    const campaigns = await prisma.campaign.findMany({
      orderBy: { createdAt: "desc" },
    });
    return NextResponse.json({ success: true, campaigns });
  } catch (error: any) {
    console.error("[API/campaigns GET] Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { action, goal, audience, campaignData } = body;

    if (action === "GENERATE") {
      const catalog = await prisma.product.findMany({ take: 10 });
      const generated = await aiEngine.generateCampaign(goal, audience, catalog);
      return NextResponse.json({ success: true, plan: generated });
    }

    if (action === "CREATE") {
      const created = await prisma.campaign.create({
        data: {
          name: campaignData.name,
          goal: campaignData.goal,
          targetAudience: campaignData.targetAudience,
          message: campaignData.message,
          recommendedProductIds: JSON.stringify(campaignData.recommendedProductIds || []),
          status: "ACTIVE",
          expectedImpact: campaignData.expectedImpact || "+20% Conversion",
          aiReasoning: campaignData.aiReasoning || "Generated by Growth Insights Agent",
        },
      });

      await prisma.activityLog.create({
        data: {
          actor: "Growth Insights Agent",
          agentKey: "GROWTH",
          action: `Activated Campaign: "${created.name}"`,
          entityType: "Campaign",
          entityId: created.id,
          outcome: "Active",
          details: `Targeting: ${created.targetAudience}`,
        },
      });

      return NextResponse.json({ success: true, campaign: created });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (error: any) {
    console.error("[API/campaigns POST] Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
